wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.5
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 50
layers:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.01
loss:
  desc: null
  value: mse
